package com.gp.dao.model;

import java.util.Date;

public class GpPubgPlayer extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gp_pubg_player.player_id
     *
     * @mbg.generated
     */
    private Long playerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gp_pubg_player.player_type
     *
     * @mbg.generated
     */
    private String playerType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gp_pubg_player.created_time
     *
     * @mbg.generated
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gp_pubg_player.match_data
     *
     * @mbg.generated
     */
    private String matchData;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gp_pubg_player.player_id
     *
     * @return the value of gp_pubg_player.player_id
     *
     * @mbg.generated
     */
    public Long getPlayerId() {
        return playerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gp_pubg_player.player_id
     *
     * @param playerId the value for gp_pubg_player.player_id
     *
     * @mbg.generated
     */
    public void setPlayerId(Long playerId) {
        this.playerId = playerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gp_pubg_player.player_type
     *
     * @return the value of gp_pubg_player.player_type
     *
     * @mbg.generated
     */
    public String getPlayerType() {
        return playerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gp_pubg_player.player_type
     *
     * @param playerType the value for gp_pubg_player.player_type
     *
     * @mbg.generated
     */
    public void setPlayerType(String playerType) {
        this.playerType = playerType == null ? null : playerType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gp_pubg_player.created_time
     *
     * @return the value of gp_pubg_player.created_time
     *
     * @mbg.generated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gp_pubg_player.created_time
     *
     * @param createdTime the value for gp_pubg_player.created_time
     *
     * @mbg.generated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gp_pubg_player.match_data
     *
     * @return the value of gp_pubg_player.match_data
     *
     * @mbg.generated
     */
    public String getMatchData() {
        return matchData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gp_pubg_player.match_data
     *
     * @param matchData the value for gp_pubg_player.match_data
     *
     * @mbg.generated
     */
    public void setMatchData(String matchData) {
        this.matchData = matchData == null ? null : matchData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gp_pubg_player
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", playerId=").append(playerId);
        sb.append(", playerType=").append(playerType);
        sb.append(", createdTime=").append(createdTime);
        sb.append(", matchData=").append(matchData);
        sb.append("]");
        sb.append(", from super class ");
        sb.append(super.toString());
        return sb.toString();
    }
}