package com.gp.dao.model;

import java.util.Date;

public class GpPubgMatchData extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gp_pubg_match_data.match_id
     *
     * @mbg.generated
     */
    private Long matchId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gp_pubg_match_data.match_data
     *
     * @mbg.generated
     */
    private String matchData;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gp_pubg_match_data.participants
     *
     * @mbg.generated
     */
    private String participants;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gp_pubg_match_data.start_time
     *
     * @mbg.generated
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gp_pubg_match_data.end_time
     *
     * @mbg.generated
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gp_pubg_match_data.player_id
     *
     * @mbg.generated
     */
    private Long playerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gp_pubg_match_data.match_id
     *
     * @return the value of gp_pubg_match_data.match_id
     *
     * @mbg.generated
     */
    public Long getMatchId() {
        return matchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gp_pubg_match_data.match_id
     *
     * @param matchId the value for gp_pubg_match_data.match_id
     *
     * @mbg.generated
     */
    public void setMatchId(Long matchId) {
        this.matchId = matchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gp_pubg_match_data.match_data
     *
     * @return the value of gp_pubg_match_data.match_data
     *
     * @mbg.generated
     */
    public String getMatchData() {
        return matchData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gp_pubg_match_data.match_data
     *
     * @param matchData the value for gp_pubg_match_data.match_data
     *
     * @mbg.generated
     */
    public void setMatchData(String matchData) {
        this.matchData = matchData == null ? null : matchData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gp_pubg_match_data.participants
     *
     * @return the value of gp_pubg_match_data.participants
     *
     * @mbg.generated
     */
    public String getParticipants() {
        return participants;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gp_pubg_match_data.participants
     *
     * @param participants the value for gp_pubg_match_data.participants
     *
     * @mbg.generated
     */
    public void setParticipants(String participants) {
        this.participants = participants == null ? null : participants.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gp_pubg_match_data.start_time
     *
     * @return the value of gp_pubg_match_data.start_time
     *
     * @mbg.generated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gp_pubg_match_data.start_time
     *
     * @param startTime the value for gp_pubg_match_data.start_time
     *
     * @mbg.generated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gp_pubg_match_data.end_time
     *
     * @return the value of gp_pubg_match_data.end_time
     *
     * @mbg.generated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gp_pubg_match_data.end_time
     *
     * @param endTime the value for gp_pubg_match_data.end_time
     *
     * @mbg.generated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gp_pubg_match_data.player_id
     *
     * @return the value of gp_pubg_match_data.player_id
     *
     * @mbg.generated
     */
    public Long getPlayerId() {
        return playerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gp_pubg_match_data.player_id
     *
     * @param playerId the value for gp_pubg_match_data.player_id
     *
     * @mbg.generated
     */
    public void setPlayerId(Long playerId) {
        this.playerId = playerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gp_pubg_match_data
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", matchId=").append(matchId);
        sb.append(", matchData=").append(matchData);
        sb.append(", participants=").append(participants);
        sb.append(", startTime=").append(startTime);
        sb.append(", endTime=").append(endTime);
        sb.append(", playerId=").append(playerId);
        sb.append("]");
        sb.append(", from super class ");
        sb.append(super.toString());
        return sb.toString();
    }
}