package com.gp.dao.mapper;

import com.gp.dao.model.GpPubgPlayer;
import com.gp.dao.model.GpPubgPlayerExample;
import java.util.List;
import java.util.Map;

public interface GpPubgPlayerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gp_pubg_player
     *
     * @mbg.generated
     */
    long countByExample(GpPubgPlayerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gp_pubg_player
     *
     * @mbg.generated
     */
    int deleteById(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gp_pubg_player
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(GpPubgPlayer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gp_pubg_player
     *
     * @mbg.generated
     */
    int insertMapSelective(Map<String, Object> record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gp_pubg_player
     *
     * @mbg.generated
     */
    int insertSelective(GpPubgPlayer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gp_pubg_player
     *
     * @mbg.generated
     */
    List<GpPubgPlayer> selectByExample(GpPubgPlayerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gp_pubg_player
     *
     * @mbg.generated
     */
    GpPubgPlayer selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gp_pubg_player
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GpPubgPlayer record);
}